### ISSUE TITLE
Could you share the method to create printed-palette.png?

### ISSUE THREAD

**Issue by theFool32** [mahmoods01/accessorize-to-a-crime#1]
Hi, it seems the printed-palette.png is printer-related. I wonder how could I create such an image.

Thanks a lot. :)

**Comment by mahmoods01** [comment]
Hi, Jie. You can produce one for your printer by printing and scanning the attached image.

![ideal-palette](https://user-images.githubusercontent.com/40036200/86170068-40955780-bb23-11ea-9ff7-cc349af2eb7a.jpg)

**Comment by theFool32** [comment]
Thanks for your help. 👍
